- hosts: kube_master
  tasks:
  - name: Make dir
    shell: mkdir -p $HOME/.kube

  - name: Copy config
    shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

  - name: Change owner
    shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config